/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package generate.pdf;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.Test;

import java.io.*;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTest {

    @Test
    public void shouldGeneratePdfWithHelloWorld() {
        var testee = new App();

        var model = Map.of(
                "title", "Hello world!",
                "pages", List.of(1, 2, 3));

        var pdf = testee.generatePdf(model);
        save(pdf);

        var pdfAsText = pdfToText(pdf);

        assertThat(pdfAsText).contains("Hello world!");
    }

    private void save(byte[] pdf) {
        try (OutputStream out = new BufferedOutputStream(new FileOutputStream(new File("build/generated.pdf")))) {
            out.write(pdf);
        } catch (IOException e) {
            throw new RuntimeException();
        }
    }

    private String pdfToText(byte[] pdf) {
        try (PDDocument document = PDDocument.load(pdf)) {
            return new PDFTextStripper().getText(document);
        } catch (IOException e) {
            throw new RuntimeException();
        }
    }

}
